### ISSUE TITLE
Incorrect 'Location' returned by 'OnTraceHit_Event'

### ISSUE THREAD

**Issue by Soliax** [rlewicki/MeleeTrace#14] opened 2024-03-27 11:49 UTC
Hello,

Firstly, I'd like to acknowledge that while I'm not an expert in UE5, I've encountered a peculiar issue with your plugin. 
Here's a breakdown of the problem:

- The location returned is accurate when using the **LINE** shape.
- However, the location returned is inaccurate when using either the **SPHERE** or **CUBE** shapes.
- With the **CAPSULE** shape, the returned location yields inconsistent results. It seems correct when the hit occurs on the line between capsules, but incorrect when the capsule itself is the source of the hit.

Here are the configurations for the Melee Trace:

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/f1a30eef-12b8-4ca8-9f04-38d771bebcf9)

And for the Animation montage:

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/630ea425-08c9-4dcf-b625-a89d8de396fd)

Additionally, here's the Blueprint AI code:

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/2cb9be2f-9330-4dd4-86e2-c817ebbfec80)

Regarding the location issue, here's an example:

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/394791aa-8829-4c47-b50c-79bb59e1eab3)

As illustrated, the returned location vector in such cases is completely incorrect. Conversely, when using a line, the hit location returned is accurate.

Could you kindly advise if I've overlooked something, or if the issue lies within your plugin?

Note: In the example, I'd expect only one sphere to be drawn, but as observed, multiple spheres are drawn (although this doesn't seem to be the root cause of the incorrect location behavior).

Aside from this issue, I'd like to express my gratitude for your plugin; it's truly amazing and remarkably easy to use.

**Comment by Soliax** [comment] 2024-03-27 11:56
Engine version : 5.3.2

**Comment by rlewicki** [comment] 2024-03-27 22:03
Hi @Soliax, first of all, thank you for reaching out and posting very detailed description of a potential issue.

> Note: In the example, I'd expect only one sphere to be drawn, but as observed, multiple spheres are drawn (although this doesn't seem to be the root cause of the incorrect location behavior).

Looking at the `Melee Trace` anim notify state definition in the montage you posted in seems it's duration is  one frame only so it indeed should only draw 1 sphere rather than multiple spheres. I do not have such case covered in my testing playground so I will add it and inspect if there is anything weird happening.

For the first part regarding all shapes other than line being drawn incorrectly, I haven't really noticed anything strange in my testing. I'm using all of the shapes with a melee sword animations and them seem to be acting alright:
![image](https://github.com/rlewicki/MeleeTrace/assets/10658394/f8c34afc-4fc8-4db4-8e9d-b0aa9dd5e25a)

This however brings lack of information in the debug drawings. To be able to tell whether these shape are drawn correctly the debug drawing should also include:
a. sockets it's using as start and end location
b. center location of each interpolated point instead  just shape (not relevant in case of the line trace)

I will also try get the debug drawings inside the animation editor so it's much easier to setup without going into PIE.

Let me know if you have any further questions!

**Comment by Soliax** [comment] 2024-03-28 01:59
Hi @rlewicki,

Perhaps I wasn't sufficiently clear, but the primary concern does not pertain to the traces being drawn incorrectly. Throughout my testing, all shapes drawn appear to align perfectly with the animation. The problem lies with the returned 'Location' value upon a hit. For some inexplicable reason, it provided me with this weird value:

X=1649267701760.000 Y=8192.002 Z=0.008

As I previously elucidated, when employing a line shape, the computed value for the 'Location' output variable in the event 'On Trace Hit' is accurate, whereas for other shapes, it proves to be incorrect.

**Comment by rlewicki** [comment] 2024-03-28 05:28
Ah, this make much more sense now! Sorry about the confusion. I'll take a look at it now

**Comment by rlewicki** [comment] 2024-03-28 06:47
Okay, I've prepared a gym where I h ave animation with each shape hitting a target in front and then drawing magenta  spheres in the hit locations. Here is a video of the test:

https://github.com/rlewicki/MeleeTrace/assets/10658394/0b4baa84-48f5-4ea9-8c65-0695583e397c

And here is the blueprint for the above test:
![image](https://github.com/rlewicki/MeleeTrace/assets/10658394/602b167c-c5a5-43eb-a32f-c1307938a26e)

Honestly it seems that the `HitLocation` for all the shapes is correct. Can you think of any other test I could prepare to try to reproduce your case?

**Comment by Soliax** [comment] 2024-03-28 22:43
Concerned about potential issues affecting my project's test results, I opted for the simplest testing approach:

1. Initialized a project using the **Third Person** template.
2. Enabled the **Melee Trace** plugin.
3. Imported the **Kick.FBX** file using **SK_Mannequin**

[Kick.zip](https://github.com/rlewicki/MeleeTrace/files/14796179/Kick.zip)

4. Created an **Animation Montage** for the **Kick** **Animation Sequence**.
5. Configured the **Kick_Montage** according to the provided specifications.

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/188da838-8d47-4044-979b-d8f06d4403cb)

6. Added **MeleeTrace** to **BP_ThirdPersonCharacter**
7. Integrated the provided code into **BP_ThirdPersonCharacter**.

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/f7c97854-5cae-47d6-aa4f-83bc571e76f0)

8. Launched the editor.
9. Triggered the kick action by pressing **K** on the keyboard.

Results:

![image](https://github.com/rlewicki/MeleeTrace/assets/18615230/9a28cc10-09e3-42ba-b3e4-95f88b064ad4)

- Multiple spheres were generated by the Melee Trace.
- No debug sphere was drawn on the floor.
- Received a hit location value of X=0.000, Y=0.000, Z=0.000.

Note: The character did not execute the animation as it is not fully set up for such actions by default. However, I aimed to maintain simplicity throughout the testing process.

Hope this test is legit, as I might have made it too simple, but I wasn't able to track anything wrong on my project.

**Comment by rlewicki** [comment] 2024-03-29 09:25
This is great, thank you very much for detailed steps. I'm setting it up now and will let you know what I find.

**Comment by rlewicki** [comment] 2024-03-29 10:09
Fix submitted in 063d57a in case you would like to inspect it yourself.

**Comment by rlewicki** [comment] 2024-03-29 12:01
Actually I kept investigating this one and it turns out this is an issue with the physics engine implementation (Chaos). If you perform a sweep with start and end location being almost identical the engine doesn't properly recognize the impact point.

To mitigate this issue I'm checking whether sweep start and end are equals and if yes, I'm adding a `KINDA_SMALL_NUMBER` to the previous frame sample. This shouldn't have any meaningful impact on the precision of the trace but solves the issue in the example you presented above.

**Comment by rlewicki** [comment] 2024-03-29 12:29
Closing the issue as this has been now submitted in release v1.4.0

Thanks once again :)

**Closed by rlewicki** 2024-03-29 12:29 UTC
Labels: bug
